/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "../components/ui/sonner";
import ClientProviders from "../components/Providers";
import { ThemeProvider } from "../components/utils/ThemeProvider";
import clsx from "clsx";
import { ClerkProvider } from "@clerk/nextjs";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alex's Nest",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <ClerkProvider>
        <ClientProviders>
          <body className={clsx(inter.className)}>
            <NextIntlClientProvider messages={messages}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                storageKey="kotama-theme"
              >
                {children}
                <Toaster />
              </ThemeProvider>
            </NextIntlClientProvider>
          </body>
        </ClientProviders>
      </ClerkProvider>
    </html>
  );
}
