/** @format */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import theme from '../theme';
import { UserProvider } from '@auth0/nextjs-auth0/client';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Alex's Nest",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={theme.palette.background.primary}>
      <UserProvider>
        <body className={inter.className}>{children}</body>
      </UserProvider>
    </html>
  );
}
