/** @format */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '../components/ui/sonner';
import ClientProviders from '../components/Providers';
import { ThemeProvider } from '../components/utils/ThemeProvider';
import clsx from 'clsx';
import { UserProvider } from '@auth0/nextjs-auth0/client';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Alex's Nest",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <UserProvider>
        <ClientProviders>
          <body className={clsx(inter.className)}>
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
              enableSystem
              storageKey='kotama-theme'
            >
              {children}
              <Toaster />
            </ThemeProvider>
          </body>
        </ClientProviders>
      </UserProvider>
    </html>
  );
}
